services:
  api:
    build:
      context: ..
      dockerfile: packages/${NAME}/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/go/src

  e2e_tests:
    image: golang:1.23.6-alpine
    volumes:
      - .:/go/src/e2e-tests
      - ../api:/go/src/api
    working_dir: /go/src/e2e-tests
    command: go test ./...
    environment:
      - API_BASE_URL=http://api:8080
