networks:
  benchmark_stack:
    driver: bridge
    name: benchmark_stack

services:
  database:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=benchmark
      - POSTGRES_PASSWORD=benchmark
      - POSTGRES_DB=benchmark
    ports:
      - "5432:5432"
    volumes:
      - "../.local-env/stack/postgres:/var/lib/postgresql/data"
    networks:
      - "benchmark_stack"


