version: '3.8'

networks:
  monitoring_network:
    driver: bridge
    name: monitoring_network

services:
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"
    networks:
      - monitoring_network
    environment:
      - INFLUXDB_DB=k6
      - INFLUXDB_USER=k6
      - INFLUXDB_USER_PASSWORD=k6
    volumes:
      - ../.local/influxdb:/var/lib/influxdb
    profiles:
      - monitoring
      - test

  grafana:
    image: grafana/grafana:11.4.0
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - monitoring_network
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=secret
      - GF_SECURITY_DISABLE_INITIAL_ADMIN_PASSWORD_CHANGE=true
    volumes:
      - ../.local/grafana:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - influxdb
    profiles:
      - monitoring

  prometheus:
    image: prom/prometheus:v3.1.0
    container_name: prometheus
    ports:
      - "9090:9090"
    networks:
      - monitoring_network
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ../.local-env/monitoring/prometheus:/etc/prometheus
      - ./monitoring/prometheus/config.yml:/etc/prometheus/prometheus.yml

  api:
    build:
      context: ..
      dockerfile: packages/${NAME}/Dockerfile
    container_name: benchmark-api
    ports:
      - "8080:8080"
    networks:
      - monitoring_network
    environment:
      - PORT=8080
    profiles:
      - test

  k6:
    image: grafana/k6:latest
    container_name: k6
    command: run --out influxdb=http://influxdb:8086/k6 ${TARGET} /tests/content-api.js
    volumes:
      - ./tests:/tests
    networks:
      - monitoring_network
    environment:
      - API_BASE_URL=http://api:8080
      - TARGET=${TARGET}
      - K6_INFLUXDB_ADDR=http://influxdb:8086
      - K6_INFLUXDB_DB=k6
    depends_on:
      - api
      - influxdb
    profiles:
      - test